### ISSUE TITLE
Cap/Cup with rem_junction

### ISSUE THREAD

**Issue by bosonbaas** [AlgebraicJulia/Catlab.jl#164]
I've observed that the `rem_junction` function in [wiring_diagrams/Algebraic.jl](https://github.com/epatters/Catlab.jl/blob/master/src/wiring_diagrams/Algebraic.jl) will remove `dunit` and `dcounit` connections completely. This issue is likely related to #89. 

The example I've found is 
```julia
person = Ob(FreeBicategoryRelations, :person);
F = Ob(FreeBicategoryRelations, :F);
manager = Hom(:manager, person, person);
salary = Hom(:salary, person, F);

formula = mcopy(person)⋅(id(person)⊗(mcopy(person)⋅((salary⊗(manager⋅salary))⋅dcounit(F))))
```

When this is converted to a wiring diagram and displayed, we get the following graph:
```julia
draw(to_wiring_diagram(formula))
```
![image](https://user-images.githubusercontent.com/19711695/83645524-986e8c00-a580-11ea-902a-35f762bfe5aa.png)

When `rem_junctions` is applied to this wiring diagram, we get the following graph:
```julia
draw(rem_junctions(to_wiring_diagram(formula)))
```
![image (1)](https://user-images.githubusercontent.com/19711695/83645542-9d334000-a580-11ea-8110-84562194ffae.png)

**Comment by bosonbaas** [comment]
I've noticed that the `rem_junction` replaces each junction with a `complete_layer` between junction inputs and outputs. This could be given a special case for if either the input or output have a dimension of zero, but I guess this solution is still dependent on solving #89.

**Comment by epatters** [comment]
The immediate problem here is that `rem_junctions` assumes that the biproduct laws is satisfied, so that `compose(mmerge(X), delete(X)) == otimes(delete(X), delete(X))`. This is property shown in the above pictures. What you want instead is the hypergraph category law, `compose(mmerge(X), delete(X)) == dcounit(X)`.

But, as explained at #89, there are deeper problems here. Now that undirected wiring diagrams are implemented, the solution is to use those instead for hypergraph categories.
