### ISSUE TITLE
CSet Functors

### ISSUE THREAD

**Issue by olynch** [AlgebraicJulia/Catlab.jl#201]
It seems to me that there should be a general way of defining

- Presheaf morphisms (i.e. natural transformations)
- Decorating functors from FinOrd to sets of Presheaves (i.e., a function that checks if a certain CSet has the right number of parts for a specific part, and a "mapping" function)
- Forgetful functors from the categories of Presheaves to FinOrd
- Left adjoints to those forgetful functors (which is only possible in some cases; we should pin down those specific cases).
- Decorated/structured cospan categories using the previous.

After I have done these in the specific case of whole-grained Petri nets, should I look into this? I imagine that this is somewhat dependent on #194.

Oh, also, is doing limits/colimits for CSets in the plan? I think that this wouldn't be too hard, and it seems like part of the advantage of CSets is that (co)limits can be done generically.

**Comment by jpfairbanks** [comment]
So what does the generic C-Set colimit look like? I think that gets us to structured cospans if we have the "Discrete C-Set functor" which maps `n` to "the empty presheaf on n vertices" and maps FinOrdMaps to C-Set morphisms. I think this "discrete C-Set on n elements" functor needs to be the adjoint of the forgetful functor of C-Set to FinOrd, which is analogous to counting vertices. 

If we can do structured cospans instead of decorated cospans, I think that is actually better because we get a double category where the C-Set morphisms (which are natural transformations between F,G:C-->Set) tell us about relationships between C-Sets. In the graph case this is 0-cells are vertex sets 1 cells are open graphs, 2 cells are graph homomorphisms between the open graphs that respect the adjacency structure and the boundaries.

In that sense structured cospans of C-sets is really natural (pun intended)

**Comment by epatters** [comment]
Closing this issue since I think we now have everything mentioned here, including left adjoints to forgetful functors, structured cospans of C-sets, and limits and colimits of C-sets.
