### ISSUE TITLE
C-sets as a topos

### ISSUE THREAD

**Issue by epatters** [AlgebraicJulia/Catlab.jl#276]
For any C, the category of C-sets is an [elementary topos](https://ncatlab.org/nlab/show/topos#ElementaryTopos), sometimes called a "combinatorial topos." We should implement all this structure.

We already have finite limits (#271) and finite colimits (#273), which leaves

- exponentials
- subobject classifiers

**Comment by olynch** [comment]
So, intuitionist logic is it's own reward obviously, but why is this useful?

**Comment by epatters** [comment]
I have no particular need at the moment but I figure it will come in handy at some point.

**Comment by olynch** [comment]
Leaving a comment here so that we remember this: topoi are adhesive categories, so the general idea of graph rewriting should work in an arbitrary C-set https://en.wikipedia.org/wiki/Adhesive_category.

**Comment by jpfairbanks** [comment]
For FinSet this was an exercise level problem. Are there general formulas for these constructions somewhere?

**Comment by epatters** [comment]
I looked into exponentials in C-Set. As you might expect, there is a general construction, but it seems a fair bit harder than exponentials in FinSet. Unlike limits and colimits, exponentials in C-Set are *not* computed pointwise.

The construction is covered in Section 8.7 of Awodey's CT book, and worked examples for several different graphs are in Reyes, Reyes, and Zolfagahari, Section 4.3.

If I understand correctly, the construction requires enumerating all the morphisms between two C-sets, so it's also computationally hard! OTOH, computing morphisms between C-sets is something I've been wanting to get into for a while, so it could be fun.

**Comment by jpfairbanks** [comment]
Yeah in FinSet you have the fact that Y^X is iso to Y*Y...*Y so that actually leads to a very simple construction. That seems like is true because the indexing category of FinSet is discrete. Our products functionality is like julia's built in `CartesianIndex/LinearIndex` functionality. Further evidence that "Finset is the category of array indexing." I guess it makes sense that exponentials aren't computed pointwise. The complexity of graph theory has to come from somewhere.
