### ISSUE TITLE
Slow subpart Evaluation

### ISSUE THREAD

**Issue by bosonbaas** [AlgebraicJulia/Catlab.jl#324]
It seems that the `Val` function contributes an appreciable amount to the overhead of calling functions like `subpart` and `incident`. Below is example code that showcases the speed difference between calling `subpart` and `_subpart` (running `_subpart` skips the call to `Val` from `subpart`).

```julia
using Catlab.Programs.RelationalPrograms
using Catlab.CategoricalAlgebra
using BenchmarkTools

rel = @relation (a, b) begin
    f(a, b)
end

subpart(rel, :junction)
b1 = @benchmark subpart(rel, :junction)

val_junction = Val(:junction)
CategoricalAlgebra.CSetDataStructures._subpart(rel, val_junction)
b2 = @benchmark CategoricalAlgebra.CSetDataStructures._subpart(rel, val_junction)
```
When ran on my machine, the median time of `subpart` is `4.299 μs`, whereas the median time of `_subpart` is `18.082 ns`

**Comment by epatters** [comment]
Thanks for this report Andrew. That slowdown is quite heavy and also seems totally unnecessary, so hopefully we can figure out how to work around it.

**Comment by epatters** [comment]
By pure chance, I was browsing the Julia Slack today and saw a [thread](https://julialang.slack.com/archives/C67TK21LJ/p1604864140293000) about precisely this issue: the performance implications of dispatching using `Val`. This thread will eventually disappear but you can read it for now.

One important suggestion is to use `Val{x}` and dispatch on `::Type{Val{x}}` instead of using `Val(x)` and dispatching on `::Val{x}`. (I don't think this is documented in the Julia manual.) A quick experiment suggests that making this small change already gives a big improvement.

I'll follow up with a PR tomorrow.

**Comment by epatters** [comment]
@bosonbaas and @jpfairbanks, since C-sets are important to our workflow and we want them to be performant, should we set up some permanent benchmarks to track performance over time? Is there standard tooling for this? I figure there should be, since the Julia community is generally so focused on performance.

**Comment by epatters** [comment]
@bosonbaas, with #327, where do we stand on this? Is it fast enough now?

**Comment by bosonbaas** [comment]
Yep, it's no longer showing up on the profiler!

With regards to benchmarking, I know that [PkgBenchmark.jl](https://github.com/JuliaCI/PkgBenchmark.jl) seems to be designed with Github CI in mind, so could be useful. We could also possibly use [airspeed velocity](https://github.com/airspeed-velocity/asv/) which has a really nice interface ([scipy example](https://pv.github.io/scipy-bench/)), though this would require using python as a wrapper for the julia benchmarks.

**Comment by epatters** [comment]
Awesome, thanks! I will create a spinoff issue about setting up package benchmarks.
