### ISSUE TITLE
Specifying composition patterns programmatically

### ISSUE THREAD

**Issue by shawnyama** [AlgebraicJulia/Catlab.jl#719]
The Catlab compose doesn’t work dynamically as models of various sizes need to each be specified in the `composition_pattern` or `@relation` macro before `oapply` is called. We want it so that the states to merge are recognized as a parameter:

```
function compose(models, statesToMerge)
models = {
  [nameA]: petrinet,
  [nameB]: petrinet
}
statesToMerge = {
  newName1: { [nameA]: X, [nameB]: X },
  newName2: { [nameA]: foo, [nameB]: bar}
}

### E.g. of real input
models = {
  modelA: Open(LabelledPetriNet([:S, :I, :R],
   :inf_uu => ((:S, :I) => (:I, :I)),
   :rec_u => (:I => :R)
  ))
  ,
  modelB: Open(LabelledPetriNet([:V, :Iv, :R],
   :inf_vv => ((:V, :Iv) => (:Iv, :Iv)),
   :rec_v => (:Iv => :R)
  ))
}
statesToMerge = {
  newName1: { modelA: "R", modelB: "R" },
  newName2: { modelA: "S", modelB: "V" } # States with different names should work too
}
```

We tried to make it dynamic ourselves but the `@relation` macro accepts a fixed amount of static variables. There doesn’t seem to be an easy way to inject a tuple or anything into the `@relation`.

**Comment by epatters** [comment]
A general point of Catlab design is that the various DSLs implemented by macros are supposed to be for human use only. So, as much as possible, they should be a thin, cosmetic wrapper around the underlying APIs and data structures.

In this case, the `@relation` macro is just convenient syntax for creating undirected wiring diagrams (UWDs), which are the data structures that serve as composition patterns for composing open Petri nets (and other things). So the first thing I would suggest is that if you need to create composition patterns dynamically/programmatically, that you do so using the API the UWDs. There are two ways you could do this:

1. Since UWDs are acsets on a particular [schema](https://github.com/AlgebraicJulia/Catlab.jl/blob/38132d66a259f4636409519573b5d015834f8a81/src/wiring_diagrams/Undirected.jl#L27), you can create them using the general API for acsets.
2. For convenience, there is also a [specialized API](https://github.com/AlgebraicJulia/Catlab.jl/blob/38132d66a259f4636409519573b5d015834f8a81/src/wiring_diagrams/Undirected.jl#L85) for UWDs. See the [tests](https://github.com/AlgebraicJulia/Catlab.jl/blob/master/test/wiring_diagrams/Undirected.jl) for simple examples of how to use it.
