### ISSUE TITLE
`FinFunction` does not constrain assignments to be in codomain

### ISSUE THREAD

**Issue by corybrunson** [AlgebraicJulia/Catlab.jl#751]
I'm experimenting with Catlab and wondering why i don't get an error with the following:

```julia
n = FinSet(4)
m = FinSet(2)
f = FinFunction([3,2,3,1], n, m)
```

I'm able to `pretty_table()` the result, and it shows that 1, 2, 3, and 4 are mapped to 3, 2, 3, and 1, respectively; but what does this mean when 3 is not in `m`?

This seems like it could cause unexpected composition errors, like this:

```julia
o = FinSet(1)
g = FinFunction([1, 1], m, o)
fg = compose(f, g)
#> BoundsError: attempt to access 2-element Vector{Int64} at index [[1, 2, 3, 3]]
```

Thank you for any help!

**Comment by lukem12345** [comment]
After asking around, the consensus is essentially that there are some engineering trade-offs in determining when to check whether a function is well-defined. Here, the trade-off is having fast construction of `FinFunction`s over explicitly checking at construction-time whether the provided codomain fits.

As you note, this mismatch is indeed caught at composition time.

The current behavior might be improved by:
1. Providing a function that checks that this condition is met.
2. Check at construction that this condition is met, unless some flag is set, like what happens when you use the `@inbounds` hint.

These are some suggestions raised by @epatters and paraphrased by me.
