### ISSUE TITLE
Implicit Cap/Cup dunit/dcounit

### ISSUE THREAD

**Issue by jpfairbanks** [AlgebraicJulia/Catlab.jl#89]
Now that I understand the implicit vs junctioned mmerge/mcopy. I think implicit caps and cups would be awesome. Currently only junctioned versions exist, which means you have “ghost nodes” in your feedback loops. Is the hardest part doing layout of the bended wires? What functionality needs to be implemented to get there?

**Comment by epatters** [comment]
I agree that implicit is usually better because it performs certain normalizations automatically. The real problem with implicit (co)units is not graphics or layout but the directionality of wires, especially in the self-dual case.

In a self-dual compact closed category, like **Rel** or GLA, we really want to think of the wires as *undirected*, even though we are in a *directed* wiring diagram. This is some kind of halfway house between undirected wiring diagrams (as in Fong & Spivak's graphical regular logic) and the usual directed wiring diagrams.

Practically speaking, if we implemented `d(co)unit` implicitly, which direction would the wires go? Whatever convention we chose would impose undesirable constraints because directed wires can only be composed in a directed sense.

Strange though it sounds, I think the right solution to this problem is to support directed wiring diagrams whose wires are actually undirected (meaning that the underlying LightGraphs graph is a `Graph`, not `DiGraph`). Implicit bending of wires in **Rel** should then work beautifully.

**Comment by epatters** [comment]
The solution I sketched above was never implemented, but since we now have undirected wiring diagrams, the better and more principled solution is to just use those instead of directed wiring diagrams. I'll close this issue for now, but if for some reason there is interest in the alternative we can reconsider.
