### ISSUE TITLE
Bad layout of loops in Graphviz wiring diagrams

### ISSUE THREAD

**Issue by epatters** [AlgebraicJulia/Catlab.jl#98]
Loops (traces) in wiring diagrams are supported "out of the box" by Graphviz, but the layout of loops is unreliable, depending on the diagram orientation and possibly other things:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/316610/75122066-e9501980-564e-11ea-99f6-bf7627ff59ad.png">

I can't find a Graphviz edge attribute that will fix this problem. Using an invisible node to control the edge routing would certainly work, but the implementation might be tricky.

**Comment by bosonbaas** [comment]
I have taken a shot at this, and haven't been able to find a consistent way to do this. My findings are as follows:
By removing the compass directions on the ports, we are able to achieve consistent optimal looping on the TopToBottom layout. 
<img src="https://user-images.githubusercontent.com/19711695/76095061-a4eb4480-5f91-11ea-9034-655f6ae14154.png" width="200" height="200">
<img src="https://user-images.githubusercontent.com/19711695/76095363-280c9a80-5f92-11ea-8e6c-4ce5dc2da987.png" width="200" height="200">
But then this breaks the layout for the LeftToRight layout.
<img src="https://user-images.githubusercontent.com/19711695/76095563-7c177f00-5f92-11ea-8e01-7250824529b8.png" width="200" height="125">

After trying many different port attributes and port layouts, we still have found that you either have enforced compass directions with the previous sub-optimal loop routing, or you don't have enforced compass directions and the LeftToRight layout paths loops through the node.

These problems are likely due to the fact that the graphviz dot layout engine is developed specifically for DAGs, and so is not developed for this kind of graph. Possibly look into other layout tools.

**Comment by epatters** [comment]
Thanks for digging into this. The conclusion for me is: either add invisible nodes in Graphviz to control the edge placement or switch to a different layout tool that works better with loops.

**Comment by epatters** [comment]
I am closing this as "won't fix" unless some brave soul wants to take it on. Graphviz dot layout just doesn't do well with self-loops.
